### ISSUE TITLE
Docker build fails with "invalid syntax"

### ISSUE THREAD

**Issue by MKesenheimer** [profuzzbench/profuzzbench#15]
I'm trying to build the docker image as documented in the README file:
```
docker build . -t lightftp
```

Building the docker image did not complete. Instead an error was thrown:
```
Step 4/32 : RUN chmod 777 /tmp
 ---> Using cache
 ---> 09fb8cb05d1b
Step 5/32 : RUN pip install gcovr==4.2
 ---> Running in 402799b19091
Collecting gcovr==4.2
  Downloading https://files.pythonhosted.org/packages/70/8e/55232768ba46ba2cbb10ea04f3a8cf41540ee058a4e8eb5e3ac53d190e95/gcovr-4.2-py2.py3-none-any.whl (45kB)
Collecting lxml (from gcovr==4.2)
  Downloading https://files.pythonhosted.org/packages/82/f7/d0ae1fbd16865ba1403c8c7780f848a00f7182f44dace4f1d3d1d7e4f3e4/lxml-4.8.0-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.5MB)
Collecting jinja2 (from gcovr==4.2)
  Downloading https://files.pythonhosted.org/packages/91/a5/429efc6246119e1e3fbf562c00187d04e83e54619249eb732bb423efa6c6/Jinja2-3.0.3.tar.gz (269kB)
Collecting MarkupSafe>=2.0 (from jinja2->gcovr==4.2)
  Downloading https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0hxnph/MarkupSafe/setup.py", line 26
        raise BuildFailed() from e
                               ^
    SyntaxError: invalid syntax
```

I'm on Kernel Version 5.10.102-1-MANJARO (64-bit) if this matters.

**Comment by Zhaodl1** [comment]
I have the same problem. Have you solved it?

**Comment by SDUzbh** [comment]
Maybe it's because ubuntu16.04 has pip8 installed by default. You could modify the dockerfile manually to install a newer version of pip

**Comment by mm4rks** [comment]
The problem seems to be with Python 2.7 in the Ubuntu 16.04 images: `pip install gcovr==4.2` fails due to MarkupSafe/setup.py using `raise ... from` syntax, which is not supported in Python2. Migrating images to Ubuntu 18.04 #3, or 20.04 #14, or installing Python3 inside the Docker image should fix this.
