### ISSUE TITLE
profuzzbench_plot.py

### ISSUE THREAD

**Issue by x1280** [profuzzbench/profuzzbench#16]
$ profuzzbench_plot.py -i results.csv -p live555 -r 4 -c 60 -s 1 -o cov_over_time.png
Traceback (most recent call last):
  File "/home/x/profuzzbench-master(1)/profuzzbench-master/scripts/analysis/profuzzbench_plot.py", line 96, in <module>
    main(args.csv_file, args.put, args.runs, args.cut_off, args.step, args.out_file)
  File "/home/x/profuzzbench-master(1)/profuzzbench-master/scripts/analysis/profuzzbench_plot.py", line 43, in main
    cov_total += df3.tail(1).iloc[0, 5]
  File "/home/x/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 960, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/x/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3613, in _get_value
    return series._values[index]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by thuanpv** [comment]
Can you please attach your results.csv file?

**Comment by x1280** [comment]
https://github.com/x1280/result.csv Looking forward to your reply

**Comment by thuanpv** [comment]
I think you might need to attach the file here. I cannot get it using your link.

**Comment by x1280** [comment]
[results.csv](https://github.com/profuzzbench/profuzzbench/files/8638434/results.csv)

**Comment by mm4rks** [comment]
Here it seems that timestamps are missing. Had also an `IndexError` when plotting for a single fuzzer, but issues seem only slightly related... (#19 does not fix the issue at hand, but filling in timestamps in .csv does)

**Comment by kal1x** [comment]
I have the same question. I execute profuzzbench_plot.py in profuzzbench with aflnet, but the column of time is missing.

**Comment by 0011x** [comment]
> 



> $ profuzzbench_plot.py -i results.csv -p live555 -r 4 -c 60 -s 1 -o cov_over_time.png 回溯（最近一次调用）： 文件“/home/x/profuzzbench-master(1)/profuzzbench- master/scripts/analysis/profuzzbench_plot.py”，第 96 行，在 main(args.csv_file, args.put, args.runs, args.cut_off, args.step, args.out_file) 文件“/home/x/profuzzbench- master(1)/profuzzbench-master/scripts/analysis/profuzzbench_plot.py"，第 43 行，主 cov_total += df3.tail(1).iloc[0, 5] 文件“/home/x/.local/lib /python3.8/site-packages/pandas/core/indexing.py”，第 960 行，在**getitem**中 返回 self.obj._get_value(*key, takeable=self._takeable) 文件“/home/x/.local/lib /python3.8/site-packages/pandas/core/frame.py”，第 3613 行，在_get_value中 return series._values[index] IndexError: 索引 0 超出尺寸为 0 的轴 0 的范围

May I ask if it has been resolved in the end? Can you share it

**Comment by Yuhan2001** [comment]
> I have the same question. I execute profuzzbench_plot.py in profuzzbench with aflnet, but the column of time is missing.

May I ask if it has been resolved in the end?
